openapi: 3.0.3

#  This file is part of the eliona project.
#  Copyright © 2025 Eliona by IoTEC AG. All Rights Reserved.
#  ______ _ _
# |  ____| (_)
# | |__  | |_  ___  _ __   __ _
# |  __| | | |/ _ \| '_ \ / _` |
# | |____| | | (_) | | | | (_| |
# |______|_|_|\___/|_| |_|\__,_|
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
#  BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#  NON INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
#  DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

info:
  version: 0.0.1
  title: Ontology REST API for Eliona
  description: "
    The Ontology REST API for Eliona offers access to the resources and data of an Eliona environment.
    See also [Eliona API](/).
    "
  contact:
    name: Eliona by IoTEC AG
    url: https://eliona.io
    email: hello@eliona.io
  license:
    name: MIT License

externalDocs:
  description: Find out more about Eliona App SDK
  url: https://github.com/eliona-smart-building-assistant

servers:
  - url: https://{environment}.eliona.io/ontology/v1
    variables:
      environment:
        default: name
        description: Environment name to define the server URL
  - url: https://{environment}.eliona.io/api/ontology/v1
    variables:
      environment:
        default: name
        description: Environment name to define the server URL
  - url: https://{server}/ontology/v1
    variables:
      server:
        default: somewhere:3000
        description: Server of the API
  - url: http://{server}/ontology/v1
    variables:
      server:
        default: localhost:3000
        description: Server of the API

tags:
  - name: Version
    description: API version
    externalDocs:
      url: https://www.eliona.io

paths:

  /version:
    $ref: './paths/version.yaml'

  /version/openapi.json:
    $ref: './paths/version-openapi.yaml'
