### [Points] List all points (read-only)
GET {{api-server}}/v1/points?page=20&size=5 HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Points] Get point by relative ID
GET {{api-server}}/v1/points/test_asset_type%2Ftest_temperature%2F483
X-Api-Key: {{read-only-token}}

### [Points] Get point by relative ID
GET {{api-server}}/v1/points/https%3A%2F%2Fexperimental.eliona.io%2Fpoints%2Ftest_asset_type%2Ftest_temperature%2F483
X-Api-Key: {{read-only-token}}

### [Spaces] Create space (read-write)
POST {{api-server}}/v1/points HTTP/1.1
X-Api-Key: {{read-write-token}}
Content-Type: application/json+ld

{
  "@id": "https://experimental.eliona.io/points/ExampleType/ExampleAttribute/ExamplePoint",
  "@type": "dtmi:org:brickschema:schema:Brick:Point;1",
  "@context": "https://dev.realestatecore.io/contexts/Point.jsonld"
}