### [Points] List all points (read-only)
GET {{api-server}}/v1/points?page=5&size=20 HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Points] Get point by relative ID
GET {{api-server}}/v1/points/c7b934aa-9839-59cb-914b-338b035e047b
X-Api-Key: {{read-only-token}}

### [Points] Get point by absolute ID
GET {{api-server}}/v1/points/https%3A%2F%2Fexperimental.eliona.io%2Fpoints%2Fcf468816-b4c7-53e4-9e44-308517effdcf
X-Api-Key: {{read-only-token}}

### [Spaces] Create space (read-write)
POST {{api-server}}/v1/points HTTP/1.1
X-Api-Key: {{read-write-token}}
Content-Type: application/json+ld

{
  "@id": "https://experimental.eliona.io/points/22222222%2FExamplePoint",
  "@type": "dtmi:io:eliona:Point;1",
  "@context": "https://dev.realestatecore.io/contexts/Point.jsonld",
  "typeName": "test_asset_type",
  "name": "test_message"
}