### [Spaces] List all spaces (read-only)
GET {{api-server}}/v1/spaces HTTP/1.1

### [Spaces] Get space with id (read-only)
GET {{api-server}}/v1/spaces/Test1 HTTP/1.1

### [Spaces] Get space with full id (read-only)
GET {{api-server}}/v1/spaces/https%3A%2F%2Fapps.eliona.io%2F1%2Fspaces%2FTest1 HTTP/1.1

### [Spaces] List all spaces (read-only)
POST {{api-server}}/v1/spaces HTTP/1.1
Content-Type: application/json+ld

{
  "@id": "https://apps.eliona.io/1/spaces/Test1",
  "@type": "dtmi:org:w3id:rec:Space;1",
  "@context": "https://dev.realestatecore.io/contexts/Space.jsonld",
  "name": "Test"
}